SELECT
	CONCAT('Project ',project.ID) AS NAME, 
	DATEDIFF('DAY',START_DATE,FINISH_DATE) / 30 AS MONTH_COUNT
FROM
	project
WHERE
	DATEDIFF('DAY',START_DATE,FINISH_DATE) / 30 = (SELECT MAX(DATEDIFF('DAY',START_DATE,FINISH_DATE) / 30) FROM project)

	 